export const ENDPOINTS = {
  MANAGE_USERS: "/manage-users",
  USERS: "/users",
  USER: "/user",
  CHANGE_PASSWORD: "/change-password",
  LOGIN: "/login",
  FORGET_PASSWORD: "/forget",
  RESET_PASSWORD: "/reset-password",
  LOGOUT: "/logout",
  RESTAURANT: "/restaurant",
  RESTAURANTS: "/restaurants",
  SHOW_RESTAURANT : "/resto",
  SHOW_SECTIONS: "/sections",
  SHOW_MENU: "/menus",
  SHOW_ITEMS: "/items",
  SHOW_SUPPLEMENTS: "/supplements",
  SHOW_TotalOrders: "/count",
  FIND_ITEM: "/show-item",
  SHOW_ALL_Orders:"show-all",
  GET_ALL_RESTAURANTS: "/resto",
};
